services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT}:${INTERNAL_PORT}"
    restart: unless-stopped 