services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
    ports:
      - "${BACKEND_PORT}:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT}:${INTERNAL_PORT}"
    restart: unless-stopped 